apiVersion: v1
kind: Service
metadata:
  name: php-app-svc
  labels:
    app: php-app
spec:
  type: LoadBalancer
  selector:
    app: php-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
